services:
  - type: web
    name: weddinggame
    runtime: docker
    plan: free
    region: singapore

    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: weddinggame-db
          property: connectionString

databases:
  - name: weddinggame-db
    plan: free
